### ISSUE TITLE
Stability Error Reported by Home Assistant

### ISSUE THREAD

**Issue by lightmaster** [briis/mbweather#12]
```
2020-05-05 06:16:14 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the 
event loop. This is causing stability issues. Please report issue to the custom component
author for mbweather doing I/O at custom_components/mbweather/meteobridge.py, line 45:
response = self.req.get(reqUrl)
```

**Comment by briis** [comment]
Yes, I know. I have done the conversion to Async that fixes this issue, but I am working on adding configuration from the Interface before releasing. So stay tuned, a fix will be coming.

**Comment by lightmaster** [comment]
K, just making sure you'd seen this. Was updating my SSL certs, and saw the log getting flooded with this message. I'll close this then.
