### ISSUE TITLE
[Feature Request] Config option to set Darksky units

### ISSUE THREAD

**Issue by lightmaster** [briis/mbweather#4]
I live in the US, so I like 99% of my units to be our usual imperial units, however, I use mb/hPa for pressure. Can you add the ability to set custom units under Dark Sky forecast?

**Comment by briis** [comment]
See newly opened enhancement issue, that will fix this. But only for the current values on the Weather Card. As all the forecast data is coming from Dark Sky, and I have less control on that data.
