### ISSUE TITLE
Add UV and Solar radiation sensor

### ISSUE THREAD

**Issue by scottwilliamsinaus** [briis/mbweather#9]
I would really like to be able to grab the UV and solar radiation sensor data from my Davis/meteobridge. Possible? Fantastic work on mbweather - its a great piece of work!

**Comment by briis** [comment]
Thanks.
That should not be a problem. I will create 2 new sensors with Current UV and Solar Radiation. Unfortunately I don't have that HW as I 'only' have a VUE, so I will need you to test it once released.

**Comment by scottwilliamsinaus** [comment]
Too easy. I looked at your elegant code and thought of having a go myself, but it is way over my head.

Here In Australia, solar and UV radiation are something we take a lot of notice of!

Cheers
Scott

**Comment by briis** [comment]
Hi Scott,
This is now done. If you installed through HACS, it should show up in a little while (V1.3.0) or you can force it by clicking on the integration. 
Once installed and HASS is restartet, you should see the following two new sensors:
* `sensor.mbw_uv_index`
* `sensor.mbw_solar_radiation`

Let me know if it works.

**Comment by scottwilliamsinaus** [comment]
Brilliant, thanks. Its 10pm here, so tomorrow I will get a look at it- expecting a hot and sunny day 😊. Can easily match it to my wundergound data to verify: https://www.wunderground.com/dashboard/pws/IVICTORI563#history

S

**Comment by scottwilliamsinaus** [comment]
Working perfectly! Thanks so much.

S

**Comment by briis** [comment]
You are welcome. Stay safe.
